version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: gate_control
      POSTGRES_USER: gc_user
      POSTGRES_PASSWORD: 123.pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    ports:
      - "1883:1883"   # Puerto MQTT
      - "9001:9001"   # WebSockets (opcional)
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf  # Archivo de configuración
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
